#
# this module looks for SDL2_mixer (http://www.libsdl.org) support
# it will define the following values
#
# SDL2_MIXER_INCLUDE_DIR = where SDL_mixer.h can be found
# SDL2_MIXER_LIBRARY     = the library to link against SDL2_mixer
# SDL2_MIXER_FOUND       = set to 1 if SDL2_mixer is found
#

IF(SDL2_Mixer_INCLUDE_DIRS)

  FIND_PATH(SDL2_MIXER_INCLUDE_DIR SDL2/SDL_mixer.h ${SDL2_Mixer_INCLUDE_DIRS})
  FIND_LIBRARY(SDL2_MIXER_LIBRARY SDL2_mixer ${SDL2_Mixer_LIBRARY_DIRS})

ELSE(SDL2_Mixer_INCLUDE_DIRS)

  SET(SDL2_SEARCH_PATHS
    $ENV{SDL2_MIXER_HOME}
    /usr
    /usr/local
    /opt/homebrew # Brew
    /sw # Fink
  )

  FIND_LIBRARY(SDL2_MIXER_LIBRARY SDL2_mixer ${SDL2_SEARCH_PATHS} PATH_SUFFIXES lib lib64)
  FIND_PATH(SDL2_MIXER_INCLUDE_DIR SDL_mixer.h ${SDL2_SEARCH_PATHS} PATH_SUFFIXES include/SDL2 include)

ENDIF(SDL2_Mixer_INCLUDE_DIRS)

IF(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)
  SET(SDL2_MIXER_FOUND 1 CACHE BOOL "Found SDL2_mixer library")
ELSE(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)
  SET(SDL2_MIXER_FOUND 0 CACHE BOOL "Unable to find SDL2_mixer library")
ENDIF(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)

MARK_AS_ADVANCED(
  SDL2_MIXER_INCLUDE_DIR 
  SDL2_MIXER_LIBRARY 
  SDL2_MIXER_FOUND
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_mixer REQUIRED_VARS SDL2_MIXER_INCLUDE_DIR SDL2_MIXER_LIBRARY)
